export const toolListMap: ToolList[] = [
    {
        label:"程式語言",
        lists:[
            "闡釋程式","修正程式","Commands","程式簡潔化","重構程式","正規表達式",
        ]
    },
    {
        label:"撰寫文章",
        lists:[
            "取得摘要","撰寫新聞稿",
        ]
    },
    {
        label:"市場業務",
        lists:[
            "介紹產品",
        ]
    }
]